### ISSUE TITLE
Add aantal per 100ha bos & natuur to map

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/reporting-rshiny-grofwildjacht#476] opened 2024-06-04 14:47 UTC
The unit dropdown of gerapporteerd afschot should also include aantal per 100ha bos & natuur. This unit change should be reflected on the map and the linked graphs.

**Comment by mvarewyck** [comment] 2024-06-05 09:42
duplicate of https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/385

**Closed** 2024-06-05 10:04 UTC
Labels: duplicate, enhancement
