### ISSUE TITLE
springende figuren

### ISSUE THREAD

**Issue by jimcasaer** [inbo/reporting-rshiny-grofwildjacht#317] opened 2022-06-10 08:57 UTC
ON UAT: for several figures of roe deer changing the time slider (eg 2012 - 2021 tot 2014 - 2022) results in a flikkering of the figures that does not stop -- figure seems not to load stable and timeslider continues to jump between original and old setting

should be tested if this error also occurs on other computers than mine 
if so -- error should be solved

**Comment by SanderDevisscher** [comment] 2022-06-10 10:21
I'm having the same issue!
Hotfix for after my holiday ? or hold deployment?

**Comment by SanderDevisscher** [comment] 2022-06-10 12:02
and somehow I'm now unable to reproduce purposely on both laptop & desktop ??

**Comment by SanderDevisscher** [comment] 2022-06-10 12:23
In meeting with @jimcasaer we decided to go for the hotfix scenario after my holiday and thus to deploy the app in the current state

**Comment by mvarewyck** [comment] 2022-06-15 08:03
I could reproduce for the "FIGUUR: Onderkaaklengte per jaar (INBO of Meldingsformulier)" if you change the start period to 2021 and then back.
This is due to the data being renewed before the plot could be created (stuck in a loop).
I could imagine you also experience it for other plots if you have a slow internet connection or if the server is busy.

**Comment by mvarewyck** [comment] 2022-06-15 09:27
I've implemented a fix for the flikkering loop which resolves it for "FIGUUR: Onderkaaklengte per jaar (INBO of Meldingsformulier)"

Could you please test if it's solved at your side and if not: For which settings & plots does the problem occur?

**Comment by jimcasaer** [comment] 2022-06-15 10:00
Given that Sander is in holidays -- how can I test this ?

**Comment by mvarewyck** [comment] 2022-06-17 10:11
> Given that Sander is in holidays -- how can I test this ?

I don't know how Sander sets it up at UAT (and I probably don't have access). Ideally we should test in exactly the same environment.

Alternatively: I can show how it works locally for me before/after the update during a quick call. If we can reproduce that the flikkering occurs before the update but no longer after, then it will hopefully also work on UAT.

**Comment by SanderDevisscher** [comment] 2022-10-05 10:26
seems fixed for now

**Comment by SanderDevisscher** [comment] 2022-11-09 08:47
This issue has reappaered in **PRD** !! and should be fixed asap !

https://user-images.githubusercontent.com/16779320/200782896-32e0707d-aa61-4874-a825-4c080d033f0d.mp4

**Comment by mvarewyck** [comment] 2022-11-09 09:31
(I'm on it)

**Closed** 2022-11-10 15:39 UTC
Labels: bug, DRINGEND
